export interface Badge {
  label: string;
  logo: string;
  logoColor?: string;
}

export const BADGES = {
  react: { label: "React", logo: "react", logoColor: "61DAFB" },
  nextjs: { label: "Next.js", logo: "nextdotjs", logoColor: "000000" },
  vue: { label: "Vue.js", logo: "vuedotjs", logoColor: "4FC08D" },
  svelte: { label: "Svelte", logo: "svelte", logoColor: "FF3E00" },
  typescript: { label: "TypeScript", logo: "typescript", logoColor: "3178C6" },
  javascript: { label: "JavaScript", logo: "javascript", logoColor: "F7DF1E" },
  java: { label: "Java", logo: "openjdk", logoColor: "ED8B00" },
  redux: { label: "Redux", logo: "redux", logoColor: "764ABC" },
  pinia: { label: "Pinia", logo: "vuedotjs", logoColor: "4FC08D" },
  storybook: { label: "Storybook", logo: "storybook", logoColor: "FF4785" },
  chromatic: { label: "Chromatic", logo: "chromatic", logoColor: "F25C7E" },
  jest: { label: "Jest", logo: "jest", logoColor: "C21325" },
  rtl: { label: "Testing Library", logo: "testinglibrary", logoColor: "E33332" },
  cypress: { label: "Cypress", logo: "cypress", logoColor: "17202C" },
  playwright: { label: "Playwright", logo: "playwright", logoColor: "2EAD33" },
  threejs: { label: "Three.js", logo: "threedotjs", logoColor: "000000" },
  webrtc: { label: "WebRTC", logo: "webrtc", logoColor: "333333" },
  websocket: { label: "WebSocket", logo: "socketdotio", logoColor: "010101" },
  livekit: { label: "LiveKit", logo: "livekit", logoColor: "000000" },
  springboot: { label: "Spring Boot", logo: "springboot", logoColor: "6DB33F" },
  nodejs: { label: "Node.js", logo: "nodedotjs", logoColor: "339933" },
  docker: { label: "Docker", logo: "docker", logoColor: "2496ED" },
  kubernetes: { label: "Kubernetes", logo: "kubernetes", logoColor: "326CE5" },
  jenkins: { label: "Jenkins", logo: "jenkins", logoColor: "D24939" },
  haproxy: { label: "HAProxy", logo: "haproxy", logoColor: "000000" },
  prometheus: { label: "Prometheus", logo: "prometheus", logoColor: "E6522C" },
  grafana: { label: "Grafana", logo: "grafana", logoColor: "F46800" },
  jmeter: { label: "JMeter", logo: "apachejmeter", logoColor: "D22128" },
  kafka: { label: "Kafka", logo: "apachekafka", logoColor: "231F20" },
  redis: { label: "Redis", logo: "redis", logoColor: "DC382D" },
  mongodb: { label: "MongoDB", logo: "mongodb", logoColor: "47A248" },
  mariadb: { label: "MariaDB", logo: "mariadb", logoColor: "003545" },
  s3: { label: "Amazon S3", logo: "amazons3", logoColor: "569A31" },
  indexeddb: { label: "IndexedDB", logo: "databricks", logoColor: "FF3621" },
  pwa: { label: "PWA", logo: "pwa", logoColor: "5A0FC8" },
  webview: { label: "WebView", logo: "googlechrome", logoColor: "4285F4" },
  figma: { label: "Figma", logo: "figma", logoColor: "F24E1E" },
  git: { label: "Git", logo: "git", logoColor: "F05032" },
  github: { label: "GitHub", logo: "github", logoColor: "181717" },
  notion: { label: "Notion", logo: "notion", logoColor: "000000" },
  sentry: { label: "Sentry", logo: "sentry", logoColor: "362D59" },
  jquery: { label: "jQuery", logo: "jquery", logoColor: "0769AD" },
  html: { label: "HTML5", logo: "html5", logoColor: "E34F26" },
  css: { label: "CSS3", logo: "css3", logoColor: "1572B6" },
  swr: { label: "SWR", logo: "vercel", logoColor: "000000" },
  i18n: { label: "i18n", logo: "i18next", logoColor: "26A69A" },
  argocd: { label: "ArgoCD", logo: "argo", logoColor: "EF7B4D" },
  linux: { label: "Linux", logo: "linux", logoColor: "FCC624" },
  webgl: { label: "WebGL", logo: "webgl", logoColor: "990000" },
  confluence: { label: "Confluence", logo: "confluence", logoColor: "172B4D" },
  reactquery: { label: "React Query", logo: "reactquery", logoColor: "FF4154" },
  zustand: { label: "Zustand", logo: "react", logoColor: "443E38" },
  tailwind: { label: "Tailwind CSS", logo: "tailwindcss", logoColor: "06B6D4" },
  framer: { label: "Framer Motion", logo: "framer", logoColor: "0055FF" },
  webpack: { label: "Webpack", logo: "webpack", logoColor: "8DD6F9" },
  circleci: { label: "CircleCI", logo: "circleci", logoColor: "343434" },
  codecov: { label: "Codecov", logo: "codecov", logoColor: "F01F7A" },
  jira: { label: "Jira", logo: "jira", logoColor: "0052CC" },
  netlify: { label: "Netlify", logo: "netlify", logoColor: "00C7B7" },
  msw: { label: "MSW", logo: "mockserviceworker", logoColor: "FF6A33" },
  emotion: { label: "Emotion", logo: "emotion", logoColor: "D36AC2" },
  firebase: { label: "Firebase", logo: "firebase", logoColor: "DD2C00" },
  kotlin: { label: "Kotlin", logo: "kotlin", logoColor: "7F52FF" },
  go: { label: "Go", logo: "go", logoColor: "00ADD8" },
  mysql: { label: "MySQL", logo: "mysql", logoColor: "4479A1" },
  postgresql: { label: "PostgreSQL", logo: "postgresql", logoColor: "4169E1" },
  nginx: { label: "Nginx", logo: "nginx", logoColor: "009639" },
  gcp: { label: "GCP", logo: "googlecloud", logoColor: "4285F4" },
  openai: { label: "OpenAI", logo: "openai", logoColor: "412991" },
  aws: { label: "AWS", logo: "amazonaws", logoColor: "232F3E" },
  vite: { label: "Vite", logo: "vite", logoColor: "646CFF" },
  zod: { label: "Zod", logo: "zod", logoColor: "3E67B1" },
  radix: { label: "Radix UI", logo: "radixui", logoColor: "161618" },
  recoil: { label: "Recoil", logo: "react", logoColor: "3578E5" },
  scss: { label: "SCSS", logo: "sass", logoColor: "CC6699" },
  mui: { label: "MUI", logo: "mui", logoColor: "007FFF" },
  proj4: { label: "Proj4", logo: "openstreetmap", logoColor: "7EBC6F" },
  reactnative: { label: "React Native", logo: "react", logoColor: "61DAFB" },
  reanimated: { label: "Reanimated", logo: "react", logoColor: "001A72" },
  nativewind: { label: "NativeWind", logo: "tailwindcss", logoColor: "06B6D4" },
  mmkv: { label: "MMKV", logo: "react", logoColor: "F7A400" },
  hookform: { label: "React Hook Form", logo: "reacthookform", logoColor: "EC5990" },
  axios: { label: "Axios", logo: "axios", logoColor: "5A29E4" },
  ios: { label: "iOS", logo: "apple", logoColor: "000000" },
  android: { label: "Android", logo: "android", logoColor: "3DDC84" },
  pnpm: { label: "pnpm", logo: "pnpm", logoColor: "F69220" },
  ky: { label: "ky", logo: "javascript", logoColor: "F7DF1E" },
  shadcn: { label: "shadcn/ui", logo: "shadcnui", logoColor: "000000" },
  sse: { label: "SSE", logo: "javascript", logoColor: "F7DF1E" },
  exceljs: { label: "ExcelJS", logo: "microsoftexcel", logoColor: "217346" },
  pdfjs: { label: "pdf.js", logo: "mozilla", logoColor: "000000" },
  dndkit: { label: "dnd kit", logo: "react", logoColor: "61DAFB" },
  workbox: { label: "Workbox", logo: "googlechrome", logoColor: "4285F4" },
  escpos: { label: "ESC/POS", logo: "javascript", logoColor: "F7DF1E" },
  cesium: { label: "CesiumJS", logo: "cesium", logoColor: "6CADDF" },
  recharts: { label: "Recharts", logo: "react", logoColor: "22B5BF" },
  gradle: { label: "Gradle", logo: "gradle", logoColor: "02303A" },
  php: { label: "PHP", logo: "php", logoColor: "777BB4" },
  reactrouter: { label: "React Router", logo: "reactrouter", logoColor: "CA4245" },
  html2canvas: { label: "html2canvas", logo: "javascript", logoColor: "F7DF1E" },
  gitea: { label: "Gitea", logo: "gitea", logoColor: "609926" },
  querydsl: { label: "QueryDSL", logo: "hibernate", logoColor: "59666C" },
  supabase: { label: "Supabase", logo: "supabase", logoColor: "3FCF8E" },
  gemini: { label: "Gemini", logo: "googlegemini", logoColor: "8E75B2" },
  vercel: { label: "Vercel", logo: "vercel", logoColor: "000000" },
  vitest: { label: "Vitest", logo: "vitest", logoColor: "6E9F18" },
} satisfies Record<string, Badge>;

export type BadgeKey = keyof typeof BADGES;

export const CORE_SKILLS = [
  { title: "Frontend Core", badges: ["react", "nextjs", "typescript", "vue"] as BadgeKey[] },
  { title: "Realtime & 3D", badges: ["webrtc", "livekit", "websocket", "threejs", "webgl"] as BadgeKey[] },
  { title: "Testing & QA", badges: ["storybook", "jest", "rtl", "cypress", "playwright"] as BadgeKey[] },
  { title: "Backend & Infra", badges: ["springboot", "kotlin", "go", "docker", "kafka", "redis"] as BadgeKey[] },
] as const;

export const MORE_SKILLS = [
  { title: "Language", badges: ["javascript", "java"] as BadgeKey[] },
  { title: "Frameworks", badges: ["svelte", "zustand", "reactquery", "redux", "pinia"] as BadgeKey[] },
  { title: "Database", badges: ["mysql", "postgresql", "mongodb", "mariadb", "s3"] as BadgeKey[] },
  { title: "DevOps", badges: ["kubernetes", "jenkins", "haproxy", "nginx", "gcp"] as BadgeKey[] },
  { title: "Monitoring", badges: ["prometheus", "grafana", "jmeter", "sentry", "codecov"] as BadgeKey[] },
] as const;
