export interface Badge {
  label: string;
  /** 배지 점 색깔 — 브랜드 색. 테마별 보정은 badgeColor.ts 가 한다 */
  logoColor?: string;
}

export const BADGES = {
  react: { label: "React", logoColor: "61DAFB" },
  nextjs: { label: "Next.js", logoColor: "000000" },
  vue: { label: "Vue.js", logoColor: "4FC08D" },
  svelte: { label: "Svelte", logoColor: "FF3E00" },
  typescript: { label: "TypeScript", logoColor: "3178C6" },
  javascript: { label: "JavaScript", logoColor: "F7DF1E" },
  java: { label: "Java", logoColor: "ED8B00" },
  redux: { label: "Redux", logoColor: "764ABC" },
  pinia: { label: "Pinia", logoColor: "4FC08D" },
  storybook: { label: "Storybook", logoColor: "FF4785" },
  chromatic: { label: "Chromatic", logoColor: "F25C7E" },
  jest: { label: "Jest", logoColor: "C21325" },
  rtl: { label: "Testing Library", logoColor: "E33332" },
  cypress: { label: "Cypress", logoColor: "17202C" },
  playwright: { label: "Playwright", logoColor: "2EAD33" },
  threejs: { label: "Three.js", logoColor: "000000" },
  webrtc: { label: "WebRTC", logoColor: "333333" },
  websocket: { label: "WebSocket", logoColor: "010101" },
  livekit: { label: "LiveKit", logoColor: "000000" },
  springboot: { label: "Spring Boot", logoColor: "6DB33F" },
  nodejs: { label: "Node.js", logoColor: "339933" },
  docker: { label: "Docker", logoColor: "2496ED" },
  kubernetes: { label: "Kubernetes", logoColor: "326CE5" },
  jenkins: { label: "Jenkins", logoColor: "D24939" },
  haproxy: { label: "HAProxy", logoColor: "000000" },
  prometheus: { label: "Prometheus", logoColor: "E6522C" },
  grafana: { label: "Grafana", logoColor: "F46800" },
  jmeter: { label: "JMeter", logoColor: "D22128" },
  kafka: { label: "Kafka", logoColor: "231F20" },
  redis: { label: "Redis", logoColor: "DC382D" },
  mongodb: { label: "MongoDB", logoColor: "47A248" },
  mariadb: { label: "MariaDB", logoColor: "003545" },
  s3: { label: "Amazon S3", logoColor: "569A31" },
  indexeddb: { label: "IndexedDB", logoColor: "FF3621" },
  pwa: { label: "PWA", logoColor: "5A0FC8" },
  webview: { label: "WebView", logoColor: "4285F4" },
  figma: { label: "Figma", logoColor: "F24E1E" },
  git: { label: "Git", logoColor: "F05032" },
  github: { label: "GitHub", logoColor: "181717" },
  notion: { label: "Notion", logoColor: "000000" },
  sentry: { label: "Sentry", logoColor: "362D59" },
  jquery: { label: "jQuery", logoColor: "0769AD" },
  html: { label: "HTML5", logoColor: "E34F26" },
  css: { label: "CSS3", logoColor: "1572B6" },
  swr: { label: "SWR", logoColor: "000000" },
  i18n: { label: "i18n", logoColor: "26A69A" },
  argocd: { label: "ArgoCD", logoColor: "EF7B4D" },
  linux: { label: "Linux", logoColor: "FCC624" },
  webgl: { label: "WebGL", logoColor: "990000" },
  confluence: { label: "Confluence", logoColor: "172B4D" },
  reactquery: { label: "React Query", logoColor: "FF4154" },
  zustand: { label: "Zustand", logoColor: "443E38" },
  tailwind: { label: "Tailwind CSS", logoColor: "06B6D4" },
  framer: { label: "Framer Motion", logoColor: "0055FF" },
  webpack: { label: "Webpack", logoColor: "8DD6F9" },
  circleci: { label: "CircleCI", logoColor: "343434" },
  codecov: { label: "Codecov", logoColor: "F01F7A" },
  jira: { label: "Jira", logoColor: "0052CC" },
  netlify: { label: "Netlify", logoColor: "00C7B7" },
  msw: { label: "MSW", logoColor: "FF6A33" },
  emotion: { label: "Emotion", logoColor: "D36AC2" },
  firebase: { label: "Firebase", logoColor: "DD2C00" },
  kotlin: { label: "Kotlin", logoColor: "7F52FF" },
  go: { label: "Go", logoColor: "00ADD8" },
  mysql: { label: "MySQL", logoColor: "4479A1" },
  postgresql: { label: "PostgreSQL", logoColor: "4169E1" },
  nginx: { label: "Nginx", logoColor: "009639" },
  gcp: { label: "GCP", logoColor: "4285F4" },
  openai: { label: "OpenAI", logoColor: "412991" },
  aws: { label: "AWS", logoColor: "232F3E" },
  vite: { label: "Vite", logoColor: "646CFF" },
  zod: { label: "Zod", logoColor: "3E67B1" },
  radix: { label: "Radix UI", logoColor: "161618" },
  recoil: { label: "Recoil", logoColor: "3578E5" },
  scss: { label: "SCSS", logoColor: "CC6699" },
  mui: { label: "MUI", logoColor: "007FFF" },
  proj4: { label: "Proj4", logoColor: "7EBC6F" },
  reactnative: { label: "React Native", logoColor: "61DAFB" },
  reanimated: { label: "Reanimated", logoColor: "001A72" },
  nativewind: { label: "NativeWind", logoColor: "06B6D4" },
  mmkv: { label: "MMKV", logoColor: "F7A400" },
  hookform: { label: "React Hook Form", logoColor: "EC5990" },
  axios: { label: "Axios", logoColor: "5A29E4" },
  ios: { label: "iOS", logoColor: "000000" },
  android: { label: "Android", logoColor: "3DDC84" },
  pnpm: { label: "pnpm", logoColor: "F69220" },
  ky: { label: "ky", logoColor: "F7DF1E" },
  shadcn: { label: "shadcn/ui", logoColor: "000000" },
  sse: { label: "SSE", logoColor: "F7DF1E" },
  exceljs: { label: "ExcelJS", logoColor: "217346" },
  pdfjs: { label: "pdf.js", logoColor: "000000" },
  dndkit: { label: "dnd kit", logoColor: "61DAFB" },
  workbox: { label: "Workbox", logoColor: "4285F4" },
  escpos: { label: "ESC/POS", logoColor: "F7DF1E" },
  cesium: { label: "CesiumJS", logoColor: "6CADDF" },
  recharts: { label: "Recharts", logoColor: "22B5BF" },
  gradle: { label: "Gradle", logoColor: "02303A" },
  php: { label: "PHP", logoColor: "777BB4" },
  reactrouter: { label: "React Router", logoColor: "CA4245" },
  html2canvas: { label: "html2canvas", logoColor: "F7DF1E" },
  gitea: { label: "Gitea", logoColor: "609926" },
  querydsl: { label: "QueryDSL", logoColor: "59666C" },
  supabase: { label: "Supabase", logoColor: "3FCF8E" },
  gemini: { label: "Gemini", logoColor: "8E75B2" },
  vercel: { label: "Vercel", logoColor: "000000" },
  vitest: { label: "Vitest", logoColor: "6E9F18" },
} satisfies Record<string, Badge>;

export type BadgeKey = keyof typeof BADGES;

export const CORE_SKILLS = [
  { title: "Frontend Core", badges: ["react", "nextjs", "typescript", "vue"] as BadgeKey[] },
  { title: "Realtime & 3D", badges: ["webrtc", "livekit", "websocket", "threejs", "webgl"] as BadgeKey[] },
  { title: "Testing & QA", badges: ["storybook", "jest", "rtl", "cypress", "playwright"] as BadgeKey[] },
  { title: "Backend & Infra", badges: ["springboot", "kotlin", "go", "docker", "kafka", "redis"] as BadgeKey[] },
] as const;

export const MORE_SKILLS = [
  { title: "Language", badges: ["javascript", "java"] as BadgeKey[] },
  { title: "Frameworks", badges: ["svelte", "zustand", "reactquery", "redux", "pinia"] as BadgeKey[] },
  { title: "Database", badges: ["mysql", "postgresql", "mongodb", "mariadb", "s3"] as BadgeKey[] },
  { title: "DevOps", badges: ["kubernetes", "jenkins", "haproxy", "nginx", "gcp"] as BadgeKey[] },
  { title: "Monitoring", badges: ["prometheus", "grafana", "jmeter", "sentry", "codecov"] as BadgeKey[] },
] as const;
