export { SITE } from "./site";
export { BADGES, CORE_SKILLS, MORE_SKILLS } from "./badges";
export type { Badge, BadgeKey } from "./badges";
export { ABOUT_TRAITS, ABOUT_INTRO, MOTTO, ABOUT_STANCE, FUTURE, HERO_PROOF, DEV_SINCE, NICKNAMES } from "./about";
export type { AboutTrait, Nickname, Stance, FutureStep } from "./about";
export { COLLABORATIONS, PARTNER_ORDER } from "./collaboration";
export type { Collaboration, Partner } from "./collaboration";
export { PROJECTS } from "./projects";
export type { Project, ProjectLink, ProjectSection, ProjectShot } from "./projects";
export { CHRONICLE } from "./chronicle";
export type { ChronicleYear, ChronicleMoment } from "./chronicle";
export { BLOG_SOURCES } from "./blog";
export type { BlogPost, BlogSource } from "./blog";
export { CAREERS, workedMonths, formatMonths, devMonths } from "./careers";
export type { Career } from "./careers";
export { ACTIVITIES } from "./activities";
export type { Activity, ActivityLink } from "./activities";
export { PEER_REVIEWS } from "./reviews";
export type { PeerReview } from "./reviews";
export { EDUCATION } from "./education";
export type { Education } from "./education";
export { NAV_ITEMS } from "./nav";
export type { NavItem } from "./nav";
export { RESUME_HEADLINE, RESUME_SUMMARY, RESUME_STATS } from "./resume";
export type { ResumeStat } from "./resume";
