title: "Choi Seungeun"
email: plumxeun@gmail.com
timezone: UTC
baseurl: "/affiliates-jekyll-theme"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Chloe Choi
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: Choi
    display_name: Seungeun
    avatar: 'assets/images/sal.png'
    email: plumxeun@gmail.com
    web: https://github.com/xeunnie
    twitter: https://twitter.com/wowthemesnet
    description: "This is Chloe Choi from korea. I study Front-end Developer, author of these study posts."


# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives